"""Streamlit application for comparing teacher, SFT, and RFT plans."""

from __future__ import annotations

import json
import os
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
APP_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
load_dotenv(APP_DIR / ".env", override=True)

from common.prompts import (
    DETAILED_FINE_TUNING_SYSTEM_PROMPT,
    FINE_TUNED_SYSTEM_PROMPT,
    TEACHER_SYSTEM_PROMPT,
)
from common.scoring import score_plan
from model_comparison_app.foundry_agent_client import create_project_client, request_agent_plan

MODEL_OPTIONS = {
    "Supervised fine-tuned (SFT)": {
        "agent_name": os.environ.get("SFT_AGENT_NAME", "SupplyChainOrderFulfilmentAgent-SFT"),
        "agent_version": os.environ.get("SFT_AGENT_VERSION", "13"),
        "system_prompt": DETAILED_FINE_TUNING_SYSTEM_PROMPT,
        "prompt_profile": "Detailed SFT-v2 training prompt",
        "short": "SFT",
        "description": "Learns from curated examples produced by the teacher model.",
    },
    "Reinforcement fine-tuned (RFT)": {
        "agent_name": os.environ.get("RFT_AGENT_NAME", "SupplyChainOrderFulfilmentAgent-RFT"),
        "agent_version": os.environ.get("RFT_AGENT_VERSION", "10"),
        "system_prompt": FINE_TUNED_SYSTEM_PROMPT,
        "prompt_profile": "Thin RFT-v1 training prompt",
        "short": "RFT",
        "description": "Learns from outcome feedback generated by the allocation grader.",
    },
    "Teacher model": {
        "agent_name": os.environ.get("TEACHER_AGENT_NAME", "SupplyChainOrderFulfilmentAgent-Teacher"),
        "agent_version": os.environ.get("TEACHER_AGENT_VERSION", "2"),
        "system_prompt": TEACHER_SYSTEM_PROMPT,
        "prompt_profile": "Strengthened teacher prompt",
        "short": "Teacher",
        "description": "Uses the full natural-language business prompt without task fine-tuning.",
    },
}

SCENARIO = {
    "scenario_id": "balanced-three-order-demo",
    "family": "tight",
    "orders": [
        {
            "order_id": "O1",
            "sku": "A",
            "quantity": 3,
            "priority": 3,
            "deadline_hours": 30,
            "substitute_sku": "A2",
            "margin": 114,
        },
        {
            "order_id": "O2",
            "sku": "B",
            "quantity": 1,
            "priority": 2,
            "deadline_hours": 18,
            "substitute_sku": "B2",
            "margin": 80,
        },
        {
            "order_id": "O3",
            "sku": "C",
            "quantity": 1,
            "priority": 1,
            "deadline_hours": 30,
            "substitute_sku": None,
            "margin": 92,
        },
    ],
    "warehouses": [
        {
            "warehouse_id": "W1",
            "available": True,
            "inventory": {"A": 2, "A2": 0, "B": 2, "B2": 5, "C": 1, "D": 0},
            "shipment_capacity": 3,
            "standard_hours": 30,
            "standard_cost": 5,
            "expedite_hours": 8,
            "expedite_cost": 15,
        },
        {
            "warehouse_id": "W2",
            "available": True,
            "inventory": {"A": 4, "A2": 0, "B": 4, "B2": 4, "C": 4, "D": 0},
            "shipment_capacity": 5,
            "standard_hours": 18,
            "standard_cost": 9,
            "expedite_hours": 16,
            "expedite_cost": 17,
        },
    ],
    "expedite_budget": 45,
}

SKU_OPTIONS = ("A", "A2", "B", "B2", "C", "D")

# Larger scenario used only in Live Azure mode, editable in the UI without a redeploy.
# Recorded replay always uses the fixed three-order SCENARIO/VERIFIED_RESULTS above.
DEFAULT_LIVE_ORDERS: list[dict[str, Any]] = [
    {"order_id": "L01", "sku": "A", "quantity": 3, "priority": 3, "deadline_hours": 24, "substitute_sku": "A2", "margin": 120},
    {"order_id": "L02", "sku": "B", "quantity": 2, "priority": 2, "deadline_hours": 18, "substitute_sku": "B2", "margin": 95},
    {"order_id": "L03", "sku": "C", "quantity": 1, "priority": 1, "deadline_hours": 30, "substitute_sku": None, "margin": 70},
    {"order_id": "L04", "sku": "A2", "quantity": 2, "priority": 2, "deadline_hours": 18, "substitute_sku": "A", "margin": 110},
    {"order_id": "L05", "sku": "B2", "quantity": 1, "priority": 3, "deadline_hours": 12, "substitute_sku": "B", "margin": 130},
    {"order_id": "L06", "sku": "D", "quantity": 2, "priority": 1, "deadline_hours": 36, "substitute_sku": None, "margin": 60},
    {"order_id": "L07", "sku": "A", "quantity": 1, "priority": 2, "deadline_hours": 30, "substitute_sku": "A2", "margin": 100},
    {"order_id": "L08", "sku": "C", "quantity": 2, "priority": 3, "deadline_hours": 18, "substitute_sku": None, "margin": 140},
    {"order_id": "L09", "sku": "B", "quantity": 1, "priority": 1, "deadline_hours": 24, "substitute_sku": "B2", "margin": 75},
    {"order_id": "L10", "sku": "A2", "quantity": 1, "priority": 2, "deadline_hours": 12, "substitute_sku": "A", "margin": 105},
]

LIVE_SCENARIO_BASE = {
    "scenario_id": "ten-order-live-demo",
    "family": "tight",
    "warehouses": [
        {
            "warehouse_id": "W1",
            "available": True,
            "inventory": {"A": 8, "A2": 5, "B": 6, "B2": 4, "C": 5, "D": 6},
            "shipment_capacity": 20,
            "standard_hours": 24,
            "standard_cost": 6,
            "expedite_hours": 10,
            "expedite_cost": 14,
        },
        {
            "warehouse_id": "W2",
            "available": True,
            "inventory": {"A": 5, "A2": 7, "B": 8, "B2": 6, "C": 6, "D": 3},
            "shipment_capacity": 18,
            "standard_hours": 30,
            "standard_cost": 5,
            "expedite_hours": 14,
            "expedite_cost": 12,
        },
        {
            "warehouse_id": "W3",
            "available": True,
            "inventory": {"A": 4, "A2": 3, "B": 4, "B2": 5, "C": 5, "D": 4},
            "shipment_capacity": 15,
            "standard_hours": 18,
            "standard_cost": 8,
            "expedite_hours": 8,
            "expedite_cost": 18,
        },
    ],
    "expedite_budget": 40,
}

VERIFIED_RESULTS = {
    "Supervised fine-tuned (SFT)": {
        "plan": {
            "decisions": [
                {
                    "order_id": "O1",
                    "action": "ship",
                    "warehouse_id": "W2",
                    "sku": "A",
                    "quantity": 3,
                    "shipping_mode": "standard",
                },
                {
                    "order_id": "O2",
                    "action": "ship",
                    "warehouse_id": "W1",
                    "sku": "B",
                    "quantity": 1,
                    "shipping_mode": "expedite",
                },
                {
                    "order_id": "O3",
                    "action": "ship",
                    "warehouse_id": "W2",
                    "sku": "C",
                    "quantity": 1,
                    "shipping_mode": "standard",
                },
            ]
        },
        "usage": {"prompt_tokens": 0, "completion_tokens": 0},
        "seconds": 8.4,
        "source": "Recorded from original deployment",
    },
    "Reinforcement fine-tuned (RFT)": {
        "plan": {
            "decisions": [
                {
                    "order_id": "O1",
                    "action": "ship",
                    "warehouse_id": "W2",
                    "sku": "A",
                    "quantity": 3,
                    "shipping_mode": "standard",
                },
                {
                    "order_id": "O2",
                    "action": "ship",
                    "warehouse_id": "W2",
                    "sku": "B",
                    "quantity": 1,
                    "shipping_mode": "standard",
                },
                {
                    "order_id": "O3",
                    "action": "ship",
                    "warehouse_id": "W1",
                    "sku": "C",
                    "quantity": 1,
                    "shipping_mode": "standard",
                },
            ]
        },
        "usage": {"prompt_tokens": 0, "completion_tokens": 0},
        "seconds": 14.0,
        "source": "Recorded from original deployment",
    },
}

st.set_page_config(
    page_title="Allocation Recovery Lab",
    page_icon=":material/route:",
    layout="wide",
    initial_sidebar_state="collapsed",
)

st.markdown(
    """
<style>
:root {
  color-scheme: light;
  --cp-bg: #f7f4ef;
  --cp-bg-elevated: #fcfbf8;
  --cp-surface: #ffffff;
  --cp-surface-soft: #f5f5f5;
  --cp-border: #dedede;
  --cp-border-strong: #919191;
  --cp-text: #242424;
  --cp-text-muted: #5c5c5c;
  --cp-text-soft: #6f6f6f;
  --cp-accent: #b11f4b;
  --cp-accent-hover: #9a1a41;
  --cp-accent-soft: rgba(177, 31, 75, 0.08);
  --cp-accent-fg: #ffffff;
  --cp-success: #16a34a;
  --cp-danger: #dc2626;
  --cp-warning: #f59e0b;
  --cp-link: #0078d4;
  --cp-shadow: 0 18px 48px rgba(0, 0, 0, 0.12);
  --cp-overlay: rgba(255, 255, 255, 0.8);
  --cp-panel: rgba(255, 255, 255, 0.86);
  --cp-panel-strong: rgba(255, 255, 255, 0.96);
  --cp-sheen: rgba(255, 255, 255, 0.55);
  --cp-highlight: rgba(177, 31, 75, 0.12);
}
html[data-theme="dark"] {
  color-scheme: dark;
  --cp-bg: #3d3b3a;
  --cp-bg-elevated: #343231;
  --cp-surface: #292929;
  --cp-surface-soft: #2e2e2e;
  --cp-border: #474747;
  --cp-border-strong: #5f5f5f;
  --cp-text: #dedede;
  --cp-text-muted: #919191;
  --cp-text-soft: #b0b0b0;
  --cp-accent: #fd8ea1;
  --cp-accent-hover: #fb7b91;
  --cp-accent-soft: rgba(253, 142, 161, 0.14);
  --cp-accent-fg: #1a1a1a;
  --cp-success: #4ade80;
  --cp-danger: #f87171;
  --cp-warning: #fbbf24;
  --cp-link: #4da6ff;
  --cp-shadow: 0 18px 48px rgba(0, 0, 0, 0.32);
  --cp-overlay: rgba(41, 41, 41, 0.88);
  --cp-panel: rgba(41, 41, 41, 0.72);
  --cp-panel-strong: rgba(41, 41, 41, 0.96);
  --cp-sheen: rgba(255, 255, 255, 0.04);
  --cp-highlight: rgba(253, 142, 161, 0.12);
}
html, body, [class*="css"] { font-family: "Segoe UI", Aptos, Calibri, -apple-system, BlinkMacSystemFont, sans-serif; }
.stApp { background: var(--cp-bg); color: var(--cp-text); }
.block-container { max-width: 1480px; padding-top: 1.5rem; padding-bottom: 4rem; }
h1, h2, h3 { letter-spacing: 0; color: var(--cp-text); }
.hero-kicker { color: var(--cp-accent); font-weight: 700; font-size: 0.8rem; text-transform: uppercase; margin-bottom: 0.25rem; }
.hero-copy { color: var(--cp-text-muted); max-width: 860px; margin: 0.25rem 0 1.25rem; }
.section-label { color: var(--cp-text-muted); font-size: 0.78rem; font-weight: 700; text-transform: uppercase; margin: 1.25rem 0 0.35rem; }
.status-pass { color: var(--cp-success); font-weight: 700; }
.status-fail { color: var(--cp-danger); font-weight: 700; }
[data-testid="stMetric"] { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 10px; padding: 0.75rem; }
[data-testid="stMetricLabel"] { color: var(--cp-text-muted); }
[data-testid="stDataFrame"] { border: 1px solid var(--cp-border); border-radius: 10px; overflow: hidden; }
[data-testid="stVerticalBlockBorderWrapper"] { border-color: var(--cp-border); background: var(--cp-surface); border-radius: 10px; }
.stButton > button[kind="primary"] { background: var(--cp-accent); color: var(--cp-accent-fg); border-color: var(--cp-accent); border-radius: 10px; }
.stButton > button[kind="primary"]:hover { background: var(--cp-accent-hover); border-color: var(--cp-accent-hover); }
.stButton > button[kind="secondary"] { background: var(--cp-surface); color: var(--cp-text); border-color: var(--cp-border-strong); border-radius: 10px; }
[data-baseweb="select"] > div { background: var(--cp-surface); border-color: var(--cp-border); }
code, pre { font-family: Consolas, "Courier New", Courier, monospace; }
hr { border-color: var(--cp-border); }
</style>
""",
    unsafe_allow_html=True,
)


# Azure OpenAI Global-deployment pricing, USD per 1,000,000 tokens.
# Source: https://azure.microsoft.com/en-us/pricing/details/azure-openai/ (checked 2026-07-29).
# Reasoning tokens are billed within the output-token count, not as an addition.
MODEL_PRICING = {
    "Supervised fine-tuned (SFT)": {"model": "gpt-4.1-mini", "input_per_million": 0.40, "output_per_million": 1.60},
    "Reinforcement fine-tuned (RFT)": {"model": "o4-mini", "input_per_million": 1.10, "output_per_million": 4.40},
    "Teacher model": {"model": "gpt-5.2", "input_per_million": 1.75, "output_per_million": 14.00},
}


def estimate_cost_usd(model_name: str, usage: dict[str, Any]) -> dict[str, float]:
    """Estimate USD cost from token usage using Azure OpenAI Global pricing."""
    pricing = MODEL_PRICING[model_name]
    input_tokens = usage.get("input_tokens") or 0
    output_tokens = usage.get("output_tokens") or 0
    input_cost = input_tokens / 1_000_000 * pricing["input_per_million"]
    output_cost = output_tokens / 1_000_000 * pricing["output_per_million"]
    return {"input_cost": input_cost, "output_cost": output_cost, "total_cost": input_cost + output_cost}


def initial_results() -> dict[str, dict[str, Any]]:
    results: dict[str, dict[str, Any]] = {}
    for model_name, record in VERIFIED_RESULTS.items():
        results[model_name] = {
            **record,
            "result": score_plan(record["plan"], SCENARIO),
            "scenario": SCENARIO,
        }
    return results


if "results" not in st.session_state:
    st.session_state.results = initial_results()
if "live_orders" not in st.session_state:
    st.session_state.live_orders = [dict(order) for order in DEFAULT_LIVE_ORDERS]
if "live_expedite_budget" not in st.session_state:
    st.session_state.live_expedite_budget = LIVE_SCENARIO_BASE["expedite_budget"]
if "extra_instructions" not in st.session_state:
    st.session_state.extra_instructions = {name: "" for name in MODEL_OPTIONS}


def build_live_scenario() -> dict[str, Any]:
    """Build the Live Azure scenario from the current, user-editable orders."""
    orders: list[dict[str, Any]] = []
    for row in st.session_state.live_orders:
        order_id = str(row.get("order_id") or "").strip()
        if not order_id:
            continue
        substitute = row.get("substitute_sku")
        if isinstance(substitute, str):
            substitute = substitute.strip().upper()
        if not substitute or substitute == "NONE":
            substitute = None
        orders.append(
            {
                "order_id": order_id,
                "sku": str(row.get("sku") or "A").strip().upper(),
                "quantity": max(1, int(row.get("quantity") or 1)),
                "priority": max(1, int(row.get("priority") or 1)),
                "deadline_hours": max(1, int(row.get("deadline_hours") or 24)),
                "substitute_sku": substitute,
                "margin": max(0, int(row.get("margin") or 0)),
            }
        )
    return {**LIVE_SCENARIO_BASE, "orders": orders, "expedite_budget": max(0, int(st.session_state.live_expedite_budget))}


def run_model(model_name: str, replay: bool = False) -> None:
    if replay:
        record = VERIFIED_RESULTS[model_name]
        st.session_state.results[model_name] = {
            **record,
            "result": score_plan(record["plan"], SCENARIO),
            "scenario": SCENARIO,
            "source": "Recorded verified run · replayed locally",
        }
        return

    config = MODEL_OPTIONS[model_name]
    if not os.environ.get("AZURE_AI_PROJECT_ENDPOINT"):
        raise RuntimeError("AZURE_AI_PROJECT_ENDPOINT is not configured in model_comparison_app/.env")
    scenario = build_live_scenario()
    started = time.perf_counter()
    plan, usage = request_agent_plan(
        create_project_client(),
        config["agent_name"],
        config["agent_version"],
        scenario,
        extra_instructions=st.session_state.extra_instructions.get(model_name) or None,
    )
    st.session_state.results[model_name] = {
        "plan": plan,
        "result": score_plan(plan, scenario),
        "scenario": scenario,
        "usage": usage,
        "seconds": time.perf_counter() - started,
        "source": "Current live run",
    }


def orders_frame(scenario: dict[str, Any]) -> pd.DataFrame:
    rows = []
    for order in scenario["orders"]:
        rows.append(
            {
                "Order": order["order_id"],
                "Requested SKU": order["sku"],
                "Approved substitute": order["substitute_sku"] or "None",
                "Qty": order["quantity"],
                "Priority": order["priority"],
                "Deadline": f"{order['deadline_hours']} h",
                "Margin": f"${order['margin']}",
            }
        )
    return pd.DataFrame(rows)


def warehouses_frame(scenario: dict[str, Any]) -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "Warehouse": warehouse["warehouse_id"],
                "Status": "Available" if warehouse["available"] else "Unavailable",
                "Capacity": warehouse["shipment_capacity"],
                "Standard": f"{warehouse['standard_hours']} h / ${warehouse['standard_cost']} per unit",
                "Expedite": f"{warehouse['expedite_hours']} h / ${warehouse['expedite_cost']} per unit",
            }
            for warehouse in scenario["warehouses"]
        ]
    )


def inventory_frame(scenario: dict[str, Any]) -> pd.DataFrame:
    rows = []
    for warehouse in scenario["warehouses"]:
        rows.append({"Warehouse": warehouse["warehouse_id"], **warehouse["inventory"]})
    return pd.DataFrame(rows)


def audit_plan(plan: dict[str, Any] | None, scenario: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(plan, dict) or not isinstance(plan.get("decisions"), list):
        return {"issues": ["The model did not return a valid decisions list."], "decision_rows": []}

    orders = {order["order_id"]: order for order in scenario["orders"]}
    warehouses = {warehouse["warehouse_id"]: warehouse for warehouse in scenario["warehouses"]}
    inventory_used: dict[tuple[str, str], int] = defaultdict(int)
    capacity_used: dict[str, int] = defaultdict(int)
    expedite_spend = 0
    issues: list[str] = []
    rows = []

    for decision in plan["decisions"]:
        order = orders.get(decision.get("order_id"))
        if not order:
            issues.append(f"Unknown order {decision.get('order_id')} was returned.")
            continue
        if decision.get("action") == "defer":
            rows.append({"Order": order["order_id"], "Decision": "Defer", "Route": "-", "SKU": "-", "Qty": "-", "Delivery": "No shipment", "Cost": "$0"})
            continue
        warehouse = warehouses.get(decision.get("warehouse_id"))
        if not warehouse:
            issues.append(f"{order['order_id']} uses an unknown warehouse.")
            continue
        quantity = decision.get("quantity", 0)
        sku = decision.get("sku", "")
        mode = decision.get("shipping_mode", "")
        hours = warehouse.get(f"{mode}_hours", 0)
        unit_cost = warehouse.get(f"{mode}_cost", 0)
        cost = unit_cost * quantity
        on_time = hours <= order["deadline_hours"]
        inventory_used[(warehouse["warehouse_id"], sku)] += quantity
        capacity_used[warehouse["warehouse_id"]] += quantity
        if mode == "expedite":
            expedite_spend += cost
        rows.append(
            {
                "Order": order["order_id"],
                "Decision": mode.title(),
                "Route": warehouse["warehouse_id"],
                "SKU": sku + (" (substitute)" if sku != order["sku"] else ""),
                "Qty": quantity,
                "Delivery": f"{hours} h · {'On time' if on_time else 'Late'}",
                "Cost": f"${cost}",
            }
        )

    for (warehouse_id, sku), used in inventory_used.items():
        available = warehouses[warehouse_id]["inventory"].get(sku, 0)
        if used > available:
            issues.append(f"{warehouse_id} allocates {used} units of {sku}, but only {available} are available.")
    for warehouse_id, used in capacity_used.items():
        available = warehouses[warehouse_id]["shipment_capacity"]
        if used > available:
            issues.append(f"{warehouse_id} uses {used} units of capacity, above its limit of {available}.")
    if expedite_spend > scenario["expedite_budget"]:
        issues.append(f"Expedite spend is ${expedite_spend}, above the ${scenario['expedite_budget']} budget.")

    return {
        "issues": issues,
        "decision_rows": rows,
        "capacity_used": dict(capacity_used),
        "expedite_spend": expedite_spend,
    }


def rationale_for(model_name: str, record: dict[str, Any]) -> list[str]:
    result = record["result"]
    scenario = record["scenario"]
    audit = audit_plan(record["plan"], scenario)
    if not result["feasible"]:
        return [
            "The plan fails the operational gate, so the complete allocation receives zero reward.",
            *audit["issues"],
            "The failure is not about style: downstream execution would attempt inventory or capacity that does not exist.",
        ]

    metrics = result["metrics"]
    decisions = record["plan"].get("decisions", []) if isinstance(record["plan"], dict) else []
    expedited = [d.get("order_id") for d in decisions if isinstance(d, dict) and d.get("shipping_mode") == "expedite"]
    deferred = [d.get("order_id") for d in decisions if isinstance(d, dict) and d.get("action") == "defer"]
    rationale = [
        f"{len(scenario['orders'])} orders are covered by a feasible plan; priority-weighted on-time service is {metrics['service']:.1%}.",
        f"The plan retains {metrics['margin']:.1%} of available margin while spending \\${metrics['shipping_cost']:.0f} on shipping.",
        f"Expedite spend is \\${metrics['expedite_spend']:.0f} of the \\${scenario['expedite_budget']} budget.",
    ]
    if metrics["expedite_spend"] == 0:
        rationale.append("Every shipped order meets its deadline using standard service only, so no expedite budget is spent.")
    else:
        order_list = ", ".join(expedited) if expedited else "at least one order"
        rationale.append(f"Meeting every deadline required expediting {order_list}, which consumes part of the expedite budget.")
    if deferred:
        rationale.append(f"{len(deferred)} order(s) were deferred: {', '.join(deferred)}.")
    rationale.append("This explanation is computed from the returned plan and grader metrics; it is not hidden model chain-of-thought.")
    return rationale


def render_result(model_name: str) -> None:
    config = MODEL_OPTIONS[model_name]
    st.subheader(config["short"])
    record = st.session_state.results.get(model_name)
    model_reference = (
        "Original deployment"
        if replay_mode
        else f"Agent: {config['agent_name']} · Version {config['agent_version']}"
    )
    st.caption(f"{model_reference} · {config['description']}")
    if not record:
        st.info("No run is loaded for this model. Select Run model to generate one.")
        return

    result = record["result"]
    audit = audit_plan(record["plan"], record["scenario"])
    status_class = "status-pass" if result["feasible"] else "status-fail"
    status_label = "Feasible" if result["feasible"] else "Invalid plan"
    st.markdown(f'<span class="{status_class}">{status_label}</span> · {record["source"]}', unsafe_allow_html=True)

    metric_columns = st.columns(4)
    metric_columns[0].metric("Reward", f"{result['score']:.3f}")
    metric_columns[1].metric("Constraint gate", "Pass" if result["feasible"] else "Fail")
    metric_columns[2].metric("Latency", f"{record['seconds']:.1f} s")
    usage = record.get("usage") or {}
    cost = estimate_cost_usd(model_name, usage)
    metric_columns[3].metric("Est. cost", f"${cost['total_cost']:.4f}")

    st.markdown('<div class="section-label">Token usage &amp; estimated cost</div>', unsafe_allow_html=True)
    input_tokens = usage.get("input_tokens") or 0
    reasoning_tokens = usage.get("reasoning_tokens") or 0
    visible_output_tokens = usage.get("visible_output_tokens") or 0
    output_tokens = usage.get("output_tokens") or 0
    pricing = MODEL_PRICING[model_name]
    token_rows = [
        {"Category": "Input", "Tokens": input_tokens, "Cost": f"${cost['input_cost']:.4f}"},
        {"Category": "Reasoning (within output)", "Tokens": reasoning_tokens, "Cost": "included in output"},
        {"Category": "Visible output", "Tokens": visible_output_tokens, "Cost": "included in output"},
        {"Category": "Total output", "Tokens": output_tokens, "Cost": f"${cost['output_cost']:.4f}"},
        {"Category": "Total", "Tokens": input_tokens + output_tokens, "Cost": f"${cost['total_cost']:.4f}"},
    ]
    st.dataframe(pd.DataFrame(token_rows), use_container_width=True, hide_index=True)
    st.caption(f"Model: {pricing['model']} · ${pricing['input_per_million']:.2f}/1M input tokens · ${pricing['output_per_million']:.2f}/1M output tokens (Azure OpenAI Global pricing).")

    st.markdown('<div class="section-label">Allocation decisions</div>', unsafe_allow_html=True)
    st.dataframe(pd.DataFrame(audit["decision_rows"]), use_container_width=True, hide_index=True)

    if audit["issues"]:
        st.error("\n".join(f"• {issue}" for issue in audit["issues"]))
    elif result["feasible"]:
        st.success("Inventory, capacity, substitution, timing, quantity, and expedite-budget checks passed.")

    st.markdown('<div class="section-label">Business rationale</div>', unsafe_allow_html=True)
    for statement in rationale_for(model_name, record):
        st.markdown(f"- {statement}")


st.markdown('<div class="hero-kicker">Decision intelligence showcase</div>', unsafe_allow_html=True)
st.title("Allocation Recovery Lab")
st.markdown(
    '<div class="hero-copy">Compare two models on the same constrained recovery decision. The app validates each plan with the production-style grader and explains the operational outcome in business terms.</div>',
    unsafe_allow_html=True,
)

execution_mode = st.radio(
    "Execution mode",
    ["Recorded replay", "Live Azure"],
    horizontal=True,
    help="Recorded replay uses captured model outputs and runs the grader locally. Live Azure requires active deployments.",
)
replay_mode = execution_mode == "Recorded replay"
if replay_mode:
    st.info("Demo-safe replay is active. No Azure deployment, credentials, or network call is required.")

selector_left, selector_right, run_column = st.columns([1, 1, 0.7], vertical_alignment="bottom")
model_names = list(VERIFIED_RESULTS) if replay_mode else list(MODEL_OPTIONS)
with selector_left:
    left_model = st.selectbox("Left model", model_names, index=0)
with selector_right:
    right_candidates = [name for name in model_names if name != left_model]
    default_right = "Reinforcement fine-tuned (RFT)" if "Reinforcement fine-tuned (RFT)" in right_candidates else right_candidates[0]
    right_model = st.selectbox("Right model", right_candidates, index=right_candidates.index(default_right))
with run_column:
    action = "Replay" if replay_mode else "Run"
    run_both = st.button(f"{action} both models", type="primary", use_container_width=True, icon=":material/play_arrow:")

left_action, right_action = st.columns(2)
with left_action:
    run_left = st.button(f"{action} {MODEL_OPTIONS[left_model]['short']}", use_container_width=True, key="run_left")
with right_action:
    run_right = st.button(f"{action} {MODEL_OPTIONS[right_model]['short']}", use_container_width=True, key="run_right")

try:
    if run_both or run_left:
        with st.spinner(f"{action}ing {MODEL_OPTIONS[left_model]['short']}..."):
            run_model(left_model, replay=replay_mode)
    if run_both or run_right:
        with st.spinner(f"{action}ing {MODEL_OPTIONS[right_model]['short']}..."):
            run_model(right_model, replay=replay_mode)
except Exception as error:
    st.error(f"Model call failed: {type(error).__name__}: {error}")

st.divider()
st.header("Scenario inputs")
input_overview, instruction_panel = st.columns([1.55, 1])
with input_overview:
    if replay_mode:
        display_scenario = SCENARIO
    else:
        if not st.session_state.live_orders:
            st.session_state.live_orders = [dict(order) for order in DEFAULT_LIVE_ORDERS]
        st.caption("Edit orders below, then select Run — no code change or redeploy needed.")
        edited_orders = st.data_editor(
            pd.DataFrame(st.session_state.live_orders),
            use_container_width=True,
            hide_index=True,
            num_rows="dynamic",
            key="live_orders_editor",
            column_config={
                "order_id": st.column_config.TextColumn("Order ID", required=True),
                "sku": st.column_config.SelectboxColumn("SKU", options=list(SKU_OPTIONS), required=True),
                "quantity": st.column_config.NumberColumn("Quantity", min_value=1, step=1),
                "priority": st.column_config.NumberColumn("Priority", min_value=1, max_value=3, step=1),
                "deadline_hours": st.column_config.NumberColumn("Deadline (hours)", min_value=1, step=1),
                "substitute_sku": st.column_config.SelectboxColumn("Substitute SKU", options=["None", *SKU_OPTIONS]),
                "margin": st.column_config.NumberColumn("Margin ($)", min_value=0, step=1),
            },
        )
        st.session_state.live_orders = edited_orders.to_dict("records")
        if st.button("Reset scenario to default", key="reset-live-orders"):
            st.session_state.live_orders = [dict(order) for order in DEFAULT_LIVE_ORDERS]
            st.session_state.live_expedite_budget = LIVE_SCENARIO_BASE["expedite_budget"]
            st.rerun()
        display_scenario = build_live_scenario()

    budget_col, pressure_col, order_col = st.columns(3)
    if replay_mode:
        budget_col.metric("Expedite budget", f"${display_scenario['expedite_budget']}")
    else:
        with budget_col:
            st.session_state.live_expedite_budget = st.number_input(
                "Expedite budget ($)",
                min_value=0,
                step=5,
                value=int(st.session_state.live_expedite_budget),
                key="live_expedite_budget_input",
                help="Editable — lower it to make expedite spend a tighter constraint, or raise it to loosen it. Takes effect on the next Run, no redeploy needed.",
            )
            display_scenario = build_live_scenario()
    pressure_col.metric("Budget pressure", display_scenario["family"].title())
    order_col.metric("Orders", len(display_scenario["orders"]))
    if replay_mode:
        st.markdown('<div class="section-label">Orders</div>', unsafe_allow_html=True)
        st.dataframe(orders_frame(display_scenario), use_container_width=True, hide_index=True)
with instruction_panel:
    st.markdown('<div class="section-label">Model instructions</div>', unsafe_allow_html=True)
    prompt_tabs = st.tabs([MODEL_OPTIONS[left_model]["short"], MODEL_OPTIONS[right_model]["short"]])
    for prompt_tab, model_name in zip(prompt_tabs, (left_model, right_model)):
        with prompt_tab:
            st.text_area(
                MODEL_OPTIONS[model_name]["prompt_profile"],
                MODEL_OPTIONS[model_name]["system_prompt"],
                height=245,
                disabled=True,
                label_visibility="collapsed",
                key=f"prompt-{model_name}",
            )
            if not replay_mode:
                st.session_state.extra_instructions[model_name] = st.text_area(
                    "Additional instructions for this run (optional)",
                    value=st.session_state.extra_instructions.get(model_name, ""),
                    height=100,
                    key=f"extra-instructions-{model_name}",
                    placeholder='Optional extra guidance sent with this request, e.g. "Prefer standard shipping whenever a deadline allows it." The pinned agent\'s own instructions still apply.',
                )
    if replay_mode:
        st.caption(
            "Training prompts are shown for package provenance. Recorded replay retained the outputs, not the original request messages."
        )
    else:
        st.caption(
            "Prompt profiles are shown for package provenance. Live instructions are configured on the pinned Foundry agents; "
            "any text entered above is sent as additional guidance alongside the scenario for that run only — no redeployment needed."
        )

warehouse_column, inventory_column = st.columns([1.15, 1])
with warehouse_column:
    st.markdown('<div class="section-label">Warehouse service levels</div>', unsafe_allow_html=True)
    st.dataframe(warehouses_frame(display_scenario), use_container_width=True, hide_index=True)
with inventory_column:
    st.markdown('<div class="section-label">Inventory by SKU</div>', unsafe_allow_html=True)
    st.dataframe(inventory_frame(display_scenario), use_container_width=True, hide_index=True)

st.divider()
st.header("Model results")
result_left, result_right = st.columns(2, gap="large")
with result_left:
    with st.container(border=True):
        render_result(left_model)
with result_right:
    with st.container(border=True):
        render_result(right_model)

left_record = st.session_state.results.get(left_model)
right_record = st.session_state.results.get(right_model)
if left_record and right_record:
    st.divider()
    st.header("Run analysis")
    same_scenario = left_record["scenario"] == right_record["scenario"]
    if not same_scenario:
        st.warning(
            "These two results were produced against different scenarios — for example, orders were edited between runs, "
            "or one side still shows an earlier Recorded replay or Live run. Re-run both models after your latest edit for a fair comparison."
        )
    delta = right_record["result"]["score"] - left_record["result"]["score"]
    winner = right_model if delta > 0 else left_model if delta < 0 else None
    if winner:
        caveat = "" if same_scenario else " (different scenarios — not a fair comparison)"
        st.markdown(
            f"**{MODEL_OPTIONS[winner]['short']} leads this run by {abs(delta):.3f} reward points{caveat}.** "
            "The distinction is determined by the same deterministic grader used throughout the experiment."
        )
    else:
        st.markdown("**The two plans receive the same reward on this run.**")

    st.caption(
        "One scenario is illustrative, not statistical proof. In the completed 150-scenario RFT evaluation, "
        "RFT averaged 0.826 reward with 98% feasibility. Run the same held-out set for SFT before making a formal aggregate RFT-versus-SFT claim."
    )

    if replay_mode:
        if left_model == "Supervised fine-tuned (SFT)" and right_model == "Reinforcement fine-tuned (RFT)" and right_record["result"]["score"] > left_record["result"]["score"]:
            st.info(
                "Both plans are operationally valid and deliver every order on time. The distinction is optimization quality: "
                "SFT uses paid expedite service for O2, while RFT rearranges O2 and O3 across warehouses to avoid expedite entirely. "
                "RFT preserves full service and margin at lower shipping cost, producing the higher reward."
            )
    elif same_scenario and left_record["result"]["feasible"] and right_record["result"]["feasible"]:
        left_metrics = left_record["result"]["metrics"]
        right_metrics = right_record["result"]["metrics"]
        st.info(
            f"{MODEL_OPTIONS[left_model]['short']} spends ${left_metrics['shipping_cost']:.0f} on shipping "
            f"(${left_metrics['expedite_spend']:.0f} on expedite) at {left_metrics['service']:.1%} priority-weighted on-time service, "
            f"versus {MODEL_OPTIONS[right_model]['short']}'s ${right_metrics['shipping_cost']:.0f} "
            f"(${right_metrics['expedite_spend']:.0f} on expedite) at {right_metrics['service']:.1%}."
        )

st.divider()
st.header("What each fine-tuning method learned")
training_sft, training_rft, training_teacher = st.columns(3)
with training_sft:
    st.subheader("SFT")
    st.markdown(
        "The teacher generated three candidate plans for every fixed scenario. The best feasible response was retained only when its grader score was at least **0.75**. "
        "The enhanced dataset contained **148 training** and **38 validation** examples. SFT learns to imitate those curated target answers."
    )
with training_rft:
    st.subheader("RFT")
    st.markdown(
        "RFT trained on **300 scenarios** and validated on **60**. It generated plans during training and received outcome feedback: invalid plans scored zero; feasible plans were rewarded for priority-weighted on-time service, retained margin, and controlled cost. "
        "This repeated feedback teaches cross-order resource tradeoffs, not only answer imitation."
    )
with training_teacher:
    st.subheader("Teacher")
    st.markdown(
        "The teacher is not task fine-tuned. It receives the complete natural-language business prompt plus current operational data. It is useful as a strong prompt-only baseline and as the source of high-quality labels for SFT."
    )

with st.expander("Grader contract"):
    st.markdown(
        "- Every order must appear exactly once.\n"
        "- Unavailable warehouses, incorrect quantities, prohibited substitutions, inventory overruns, capacity overruns, and budget overruns invalidate the entire plan.\n"
        "- Feasible reward weights priority-aware on-time service at **55%**, retained margin at **25%**, and cost efficiency at **20%**.\n"
        "- Approved substitutions retain 90% of margin; late shipments retain half of their remaining margin.\n"
        "- Deferring everything is feasible but earns zero, preventing shortcut behavior."
    )

st.caption("Recorded replay uses verified outputs captured from the original deployments on this exact scenario and recomputes all grader metrics locally. Live model output can vary and requires active Azure deployments.")
