"""Streamlit application for comparing teacher, SFT, and RFT plans."""

from __future__ import annotations

import json
import os
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st
from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
load_dotenv(ROOT / ".env", override=True)

from common.model_client import create_client, request_plan
from common.prompts import (
    DETAILED_FINE_TUNING_SYSTEM_PROMPT,
    FINE_TUNED_SYSTEM_PROMPT,
    TEACHER_SYSTEM_PROMPT,
)
from common.scoring import score_plan

MODEL_OPTIONS = {
    "Supervised fine-tuned (SFT)": {
        "deployment": os.environ.get("SFT_DEPLOYMENT", ""),
        "system_prompt": DETAILED_FINE_TUNING_SYSTEM_PROMPT,
        "prompt_profile": "Detailed SFT-v2 training prompt",
        "short": "SFT",
        "description": "Learns from curated examples produced by the teacher model.",
    },
    "Reinforcement fine-tuned (RFT)": {
        "deployment": os.environ.get("RFT_DEPLOYMENT", ""),
        "system_prompt": FINE_TUNED_SYSTEM_PROMPT,
        "prompt_profile": "Thin RFT-v1 training prompt",
        "short": "RFT",
        "description": "Learns from outcome feedback generated by the allocation grader.",
    },
    "Teacher model": {
        "deployment": os.environ.get("TEACHER_DEPLOYMENT", ""),
        "system_prompt": TEACHER_SYSTEM_PROMPT,
        "prompt_profile": "Strengthened teacher prompt",
        "short": "Teacher",
        "description": "Uses the full natural-language business prompt without task fine-tuning.",
    },
}

SCENARIO = {
    "scenario_id": "balanced-three-order-demo",
    "family": "tight",
    "orders": [
        {
            "order_id": "O1",
            "sku": "A",
            "quantity": 3,
            "priority": 3,
            "deadline_hours": 30,
            "substitute_sku": "A2",
            "margin": 114,
        },
        {
            "order_id": "O2",
            "sku": "B",
            "quantity": 1,
            "priority": 2,
            "deadline_hours": 18,
            "substitute_sku": "B2",
            "margin": 80,
        },
        {
            "order_id": "O3",
            "sku": "C",
            "quantity": 1,
            "priority": 1,
            "deadline_hours": 30,
            "substitute_sku": None,
            "margin": 92,
        },
    ],
    "warehouses": [
        {
            "warehouse_id": "W1",
            "available": True,
            "inventory": {"A": 2, "A2": 0, "B": 2, "B2": 5, "C": 1, "D": 0},
            "shipment_capacity": 3,
            "standard_hours": 30,
            "standard_cost": 5,
            "expedite_hours": 8,
            "expedite_cost": 15,
        },
        {
            "warehouse_id": "W2",
            "available": True,
            "inventory": {"A": 4, "A2": 0, "B": 4, "B2": 4, "C": 4, "D": 0},
            "shipment_capacity": 5,
            "standard_hours": 18,
            "standard_cost": 9,
            "expedite_hours": 16,
            "expedite_cost": 17,
        },
    ],
    "expedite_budget": 45,
}

VERIFIED_RESULTS = {
    "Supervised fine-tuned (SFT)": {
        "plan": {
            "decisions": [
                {
                    "order_id": "O1",
                    "action": "ship",
                    "warehouse_id": "W2",
                    "sku": "A",
                    "quantity": 3,
                    "shipping_mode": "standard",
                },
                {
                    "order_id": "O2",
                    "action": "ship",
                    "warehouse_id": "W1",
                    "sku": "B",
                    "quantity": 1,
                    "shipping_mode": "expedite",
                },
                {
                    "order_id": "O3",
                    "action": "ship",
                    "warehouse_id": "W2",
                    "sku": "C",
                    "quantity": 1,
                    "shipping_mode": "standard",
                },
            ]
        },
        "usage": {"prompt_tokens": 0, "completion_tokens": 0},
        "seconds": 8.4,
        "source": "Recorded from original deployment",
    },
    "Reinforcement fine-tuned (RFT)": {
        "plan": {
            "decisions": [
                {
                    "order_id": "O1",
                    "action": "ship",
                    "warehouse_id": "W2",
                    "sku": "A",
                    "quantity": 3,
                    "shipping_mode": "standard",
                },
                {
                    "order_id": "O2",
                    "action": "ship",
                    "warehouse_id": "W2",
                    "sku": "B",
                    "quantity": 1,
                    "shipping_mode": "standard",
                },
                {
                    "order_id": "O3",
                    "action": "ship",
                    "warehouse_id": "W1",
                    "sku": "C",
                    "quantity": 1,
                    "shipping_mode": "standard",
                },
            ]
        },
        "usage": {"prompt_tokens": 0, "completion_tokens": 0},
        "seconds": 14.0,
        "source": "Recorded from original deployment",
    },
}

st.set_page_config(
    page_title="Allocation Recovery Lab",
    page_icon=":material/route:",
    layout="wide",
    initial_sidebar_state="collapsed",
)

st.markdown(
    """
<style>
:root {
  color-scheme: light;
  --cp-bg: #f7f4ef;
  --cp-bg-elevated: #fcfbf8;
  --cp-surface: #ffffff;
  --cp-surface-soft: #f5f5f5;
  --cp-border: #dedede;
  --cp-border-strong: #919191;
  --cp-text: #242424;
  --cp-text-muted: #5c5c5c;
  --cp-text-soft: #6f6f6f;
  --cp-accent: #b11f4b;
  --cp-accent-hover: #9a1a41;
  --cp-accent-soft: rgba(177, 31, 75, 0.08);
  --cp-accent-fg: #ffffff;
  --cp-success: #16a34a;
  --cp-danger: #dc2626;
  --cp-warning: #f59e0b;
  --cp-link: #0078d4;
  --cp-shadow: 0 18px 48px rgba(0, 0, 0, 0.12);
  --cp-overlay: rgba(255, 255, 255, 0.8);
  --cp-panel: rgba(255, 255, 255, 0.86);
  --cp-panel-strong: rgba(255, 255, 255, 0.96);
  --cp-sheen: rgba(255, 255, 255, 0.55);
  --cp-highlight: rgba(177, 31, 75, 0.12);
}
html[data-theme="dark"] {
  color-scheme: dark;
  --cp-bg: #3d3b3a;
  --cp-bg-elevated: #343231;
  --cp-surface: #292929;
  --cp-surface-soft: #2e2e2e;
  --cp-border: #474747;
  --cp-border-strong: #5f5f5f;
  --cp-text: #dedede;
  --cp-text-muted: #919191;
  --cp-text-soft: #b0b0b0;
  --cp-accent: #fd8ea1;
  --cp-accent-hover: #fb7b91;
  --cp-accent-soft: rgba(253, 142, 161, 0.14);
  --cp-accent-fg: #1a1a1a;
  --cp-success: #4ade80;
  --cp-danger: #f87171;
  --cp-warning: #fbbf24;
  --cp-link: #4da6ff;
  --cp-shadow: 0 18px 48px rgba(0, 0, 0, 0.32);
  --cp-overlay: rgba(41, 41, 41, 0.88);
  --cp-panel: rgba(41, 41, 41, 0.72);
  --cp-panel-strong: rgba(41, 41, 41, 0.96);
  --cp-sheen: rgba(255, 255, 255, 0.04);
  --cp-highlight: rgba(253, 142, 161, 0.12);
}
html, body, [class*="css"] { font-family: "Segoe UI", Aptos, Calibri, -apple-system, BlinkMacSystemFont, sans-serif; }
.stApp { background: var(--cp-bg); color: var(--cp-text); }
.block-container { max-width: 1480px; padding-top: 1.5rem; padding-bottom: 4rem; }
h1, h2, h3 { letter-spacing: 0; color: var(--cp-text); }
.hero-kicker { color: var(--cp-accent); font-weight: 700; font-size: 0.8rem; text-transform: uppercase; margin-bottom: 0.25rem; }
.hero-copy { color: var(--cp-text-muted); max-width: 860px; margin: 0.25rem 0 1.25rem; }
.section-label { color: var(--cp-text-muted); font-size: 0.78rem; font-weight: 700; text-transform: uppercase; margin: 1.25rem 0 0.35rem; }
.status-pass { color: var(--cp-success); font-weight: 700; }
.status-fail { color: var(--cp-danger); font-weight: 700; }
[data-testid="stMetric"] { background: var(--cp-surface); border: 1px solid var(--cp-border); border-radius: 10px; padding: 0.75rem; }
[data-testid="stMetricLabel"] { color: var(--cp-text-muted); }
[data-testid="stDataFrame"] { border: 1px solid var(--cp-border); border-radius: 10px; overflow: hidden; }
[data-testid="stVerticalBlockBorderWrapper"] { border-color: var(--cp-border); background: var(--cp-surface); border-radius: 10px; }
.stButton > button[kind="primary"] { background: var(--cp-accent); color: var(--cp-accent-fg); border-color: var(--cp-accent); border-radius: 10px; }
.stButton > button[kind="primary"]:hover { background: var(--cp-accent-hover); border-color: var(--cp-accent-hover); }
.stButton > button[kind="secondary"] { background: var(--cp-surface); color: var(--cp-text); border-color: var(--cp-border-strong); border-radius: 10px; }
[data-baseweb="select"] > div { background: var(--cp-surface); border-color: var(--cp-border); }
code, pre { font-family: Consolas, "Courier New", Courier, monospace; }
hr { border-color: var(--cp-border); }
</style>
""",
    unsafe_allow_html=True,
)


def initial_results() -> dict[str, dict[str, Any]]:
    results: dict[str, dict[str, Any]] = {}
    for model_name, record in VERIFIED_RESULTS.items():
        results[model_name] = {
            **record,
            "result": score_plan(record["plan"], SCENARIO),
        }
    return results


if "results" not in st.session_state:
    st.session_state.results = initial_results()


def run_model(model_name: str, replay: bool = False) -> None:
    if replay:
        record = VERIFIED_RESULTS[model_name]
        st.session_state.results[model_name] = {
            **record,
            "result": score_plan(record["plan"], SCENARIO),
            "source": "Recorded verified run · replayed locally",
        }
        return

    config = MODEL_OPTIONS[model_name]
    if not config["deployment"]:
        variable = {"SFT": "SFT_DEPLOYMENT", "RFT": "RFT_DEPLOYMENT", "Teacher": "TEACHER_DEPLOYMENT"}[config["short"]]
        raise RuntimeError(f"{variable} is not configured in .env")
    started = time.perf_counter()
    plan, usage = request_plan(
        create_client(),
        config["deployment"],
        SCENARIO,
        system_prompt=config["system_prompt"],
    )
    st.session_state.results[model_name] = {
        "plan": plan,
        "result": score_plan(plan, SCENARIO),
        "usage": usage,
        "seconds": time.perf_counter() - started,
        "source": "Current live run",
    }


def orders_frame() -> pd.DataFrame:
    rows = []
    for order in SCENARIO["orders"]:
        rows.append(
            {
                "Order": order["order_id"],
                "Requested SKU": order["sku"],
                "Approved substitute": order["substitute_sku"] or "None",
                "Qty": order["quantity"],
                "Priority": order["priority"],
                "Deadline": f"{order['deadline_hours']} h",
                "Margin": f"${order['margin']}",
            }
        )
    return pd.DataFrame(rows)


def warehouses_frame() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "Warehouse": warehouse["warehouse_id"],
                "Status": "Available" if warehouse["available"] else "Unavailable",
                "Capacity": warehouse["shipment_capacity"],
                "Standard": f"{warehouse['standard_hours']} h / ${warehouse['standard_cost']} per unit",
                "Expedite": f"{warehouse['expedite_hours']} h / ${warehouse['expedite_cost']} per unit",
            }
            for warehouse in SCENARIO["warehouses"]
        ]
    )


def inventory_frame() -> pd.DataFrame:
    rows = []
    for warehouse in SCENARIO["warehouses"]:
        rows.append({"Warehouse": warehouse["warehouse_id"], **warehouse["inventory"]})
    return pd.DataFrame(rows)


def audit_plan(plan: dict[str, Any] | None) -> dict[str, Any]:
    if not isinstance(plan, dict) or not isinstance(plan.get("decisions"), list):
        return {"issues": ["The model did not return a valid decisions list."], "decision_rows": []}

    orders = {order["order_id"]: order for order in SCENARIO["orders"]}
    warehouses = {warehouse["warehouse_id"]: warehouse for warehouse in SCENARIO["warehouses"]}
    inventory_used: dict[tuple[str, str], int] = defaultdict(int)
    capacity_used: dict[str, int] = defaultdict(int)
    expedite_spend = 0
    issues: list[str] = []
    rows = []

    for decision in plan["decisions"]:
        order = orders.get(decision.get("order_id"))
        if not order:
            issues.append(f"Unknown order {decision.get('order_id')} was returned.")
            continue
        if decision.get("action") == "defer":
            rows.append({"Order": order["order_id"], "Decision": "Defer", "Route": "-", "SKU": "-", "Qty": "-", "Delivery": "No shipment", "Cost": "$0"})
            continue
        warehouse = warehouses.get(decision.get("warehouse_id"))
        if not warehouse:
            issues.append(f"{order['order_id']} uses an unknown warehouse.")
            continue
        quantity = decision.get("quantity", 0)
        sku = decision.get("sku", "")
        mode = decision.get("shipping_mode", "")
        hours = warehouse.get(f"{mode}_hours", 0)
        unit_cost = warehouse.get(f"{mode}_cost", 0)
        cost = unit_cost * quantity
        on_time = hours <= order["deadline_hours"]
        inventory_used[(warehouse["warehouse_id"], sku)] += quantity
        capacity_used[warehouse["warehouse_id"]] += quantity
        if mode == "expedite":
            expedite_spend += cost
        rows.append(
            {
                "Order": order["order_id"],
                "Decision": mode.title(),
                "Route": warehouse["warehouse_id"],
                "SKU": sku + (" (substitute)" if sku != order["sku"] else ""),
                "Qty": quantity,
                "Delivery": f"{hours} h · {'On time' if on_time else 'Late'}",
                "Cost": f"${cost}",
            }
        )

    for (warehouse_id, sku), used in inventory_used.items():
        available = warehouses[warehouse_id]["inventory"].get(sku, 0)
        if used > available:
            issues.append(f"{warehouse_id} allocates {used} units of {sku}, but only {available} are available.")
    for warehouse_id, used in capacity_used.items():
        available = warehouses[warehouse_id]["shipment_capacity"]
        if used > available:
            issues.append(f"{warehouse_id} uses {used} units of capacity, above its limit of {available}.")
    if expedite_spend > SCENARIO["expedite_budget"]:
        issues.append(f"Expedite spend is ${expedite_spend}, above the ${SCENARIO['expedite_budget']} budget.")

    return {
        "issues": issues,
        "decision_rows": rows,
        "capacity_used": dict(capacity_used),
        "expedite_spend": expedite_spend,
    }


def rationale_for(model_name: str, record: dict[str, Any]) -> list[str]:
    result = record["result"]
    audit = audit_plan(record["plan"])
    if not result["feasible"]:
        return [
            "The plan fails the operational gate, so the complete allocation receives zero reward.",
            *audit["issues"],
            "The failure is not about style: downstream execution would attempt inventory or capacity that does not exist.",
        ]

    metrics = result["metrics"]
    rationale = [
        f"All three orders are covered by a feasible plan; priority-weighted on-time service is {metrics['service']:.1%}.",
        f"The plan retains {metrics['margin']:.1%} of available margin while spending \\${metrics['shipping_cost']:.0f} on shipping.",
        f"Expedite spend is \\${metrics['expedite_spend']:.0f} of the \\${SCENARIO['expedite_budget']} budget.",
    ]
    if metrics["expedite_spend"] == 0:
        rationale.append("The key move is placing O2 at W2 on standard service and O3 at lower-cost W1. Every deadline is met without using the expedite budget.")
    else:
        rationale.append("This plan is fully valid and meets every deadline, but it expedites O2 from W1 even though an all-standard allocation is available.")
    rationale.append("This explanation is computed from the returned plan and grader metrics; it is not hidden model chain-of-thought.")
    return rationale


def render_result(model_name: str) -> None:
    config = MODEL_OPTIONS[model_name]
    st.subheader(config["short"])
    record = st.session_state.results.get(model_name)
    deployment_label = "Original deployment" if replay_mode else "Deployment"
    st.caption(f"{deployment_label}: {config['deployment']} · {config['description']}")
    if not record:
        st.info("No run is loaded for this model. Select Run model to generate one.")
        return

    result = record["result"]
    audit = audit_plan(record["plan"])
    status_class = "status-pass" if result["feasible"] else "status-fail"
    status_label = "Feasible" if result["feasible"] else "Invalid plan"
    st.markdown(f'<span class="{status_class}">{status_label}</span> · {record["source"]}', unsafe_allow_html=True)

    metric_columns = st.columns(3)
    metric_columns[0].metric("Reward", f"{result['score']:.3f}")
    metric_columns[1].metric("Constraint gate", "Pass" if result["feasible"] else "Fail")
    metric_columns[2].metric("Latency", f"{record['seconds']:.1f} s")

    st.markdown('<div class="section-label">Allocation decisions</div>', unsafe_allow_html=True)
    st.dataframe(pd.DataFrame(audit["decision_rows"]), use_container_width=True, hide_index=True)

    if audit["issues"]:
        st.error("\n".join(f"• {issue}" for issue in audit["issues"]))
    elif result["feasible"]:
        st.success("Inventory, capacity, substitution, timing, quantity, and expedite-budget checks passed.")

    st.markdown('<div class="section-label">Business rationale</div>', unsafe_allow_html=True)
    for statement in rationale_for(model_name, record):
        st.markdown(f"- {statement}")


st.markdown('<div class="hero-kicker">Decision intelligence showcase</div>', unsafe_allow_html=True)
st.title("Allocation Recovery Lab")
st.markdown(
    '<div class="hero-copy">Compare two models on the same constrained recovery decision. The app validates each plan with the production-style grader and explains the operational outcome in business terms.</div>',
    unsafe_allow_html=True,
)

execution_mode = st.radio(
    "Execution mode",
    ["Recorded replay", "Live Azure"],
    horizontal=True,
    help="Recorded replay uses captured model outputs and runs the grader locally. Live Azure requires active deployments.",
)
replay_mode = execution_mode == "Recorded replay"
if replay_mode:
    st.info("Demo-safe replay is active. No Azure deployment, credentials, or network call is required.")

selector_left, selector_right, run_column = st.columns([1, 1, 0.7], vertical_alignment="bottom")
model_names = list(VERIFIED_RESULTS) if replay_mode else list(MODEL_OPTIONS)
with selector_left:
    left_model = st.selectbox("Left model", model_names, index=0)
with selector_right:
    right_candidates = [name for name in model_names if name != left_model]
    default_right = "Reinforcement fine-tuned (RFT)" if "Reinforcement fine-tuned (RFT)" in right_candidates else right_candidates[0]
    right_model = st.selectbox("Right model", right_candidates, index=right_candidates.index(default_right))
with run_column:
    action = "Replay" if replay_mode else "Run"
    run_both = st.button(f"{action} both models", type="primary", use_container_width=True, icon=":material/play_arrow:")

left_action, right_action = st.columns(2)
with left_action:
    run_left = st.button(f"{action} {MODEL_OPTIONS[left_model]['short']}", use_container_width=True, key="run_left")
with right_action:
    run_right = st.button(f"{action} {MODEL_OPTIONS[right_model]['short']}", use_container_width=True, key="run_right")

try:
    if run_both or run_left:
        with st.spinner(f"{action}ing {MODEL_OPTIONS[left_model]['short']}..."):
            run_model(left_model, replay=replay_mode)
    if run_both or run_right:
        with st.spinner(f"{action}ing {MODEL_OPTIONS[right_model]['short']}..."):
            run_model(right_model, replay=replay_mode)
except Exception as error:
    st.error(f"Model call failed: {type(error).__name__}: {error}")

st.divider()
st.header("Scenario inputs")
input_overview, instruction_panel = st.columns([1.55, 1])
with input_overview:
    budget_col, pressure_col, order_col = st.columns(3)
    budget_col.metric("Expedite budget", f"${SCENARIO['expedite_budget']}")
    pressure_col.metric("Budget pressure", SCENARIO["family"].title())
    order_col.metric("Orders", len(SCENARIO["orders"]))
    st.markdown('<div class="section-label">Orders</div>', unsafe_allow_html=True)
    st.dataframe(orders_frame(), use_container_width=True, hide_index=True)
with instruction_panel:
    st.markdown('<div class="section-label">Model instructions</div>', unsafe_allow_html=True)
    prompt_tabs = st.tabs([MODEL_OPTIONS[left_model]["short"], MODEL_OPTIONS[right_model]["short"]])
    for prompt_tab, model_name in zip(prompt_tabs, (left_model, right_model)):
        with prompt_tab:
            st.text_area(
                MODEL_OPTIONS[model_name]["prompt_profile"],
                MODEL_OPTIONS[model_name]["system_prompt"],
                height=245,
                disabled=True,
                label_visibility="collapsed",
                key=f"prompt-{model_name}",
            )
    if replay_mode:
        st.caption(
            "Training prompts are shown for package provenance. Recorded replay retained the outputs, not the original request messages."
        )
    else:
        st.caption("These are the developer prompts sent by the current live run.")

warehouse_column, inventory_column = st.columns([1.15, 1])
with warehouse_column:
    st.markdown('<div class="section-label">Warehouse service levels</div>', unsafe_allow_html=True)
    st.dataframe(warehouses_frame(), use_container_width=True, hide_index=True)
with inventory_column:
    st.markdown('<div class="section-label">Inventory by SKU</div>', unsafe_allow_html=True)
    st.dataframe(inventory_frame(), use_container_width=True, hide_index=True)

st.divider()
st.header("Model results")
result_left, result_right = st.columns(2, gap="large")
with result_left:
    with st.container(border=True):
        render_result(left_model)
with result_right:
    with st.container(border=True):
        render_result(right_model)

left_record = st.session_state.results.get(left_model)
right_record = st.session_state.results.get(right_model)
if left_record and right_record:
    st.divider()
    st.header("Run analysis")
    delta = right_record["result"]["score"] - left_record["result"]["score"]
    winner = right_model if delta > 0 else left_model if delta < 0 else None
    if winner:
        st.markdown(
            f"**{MODEL_OPTIONS[winner]['short']} leads this run by {abs(delta):.3f} reward points.** "
            "The distinction is determined by the same deterministic grader used throughout the experiment."
        )
    else:
        st.markdown("**The two plans receive the same reward on this run.**")

    st.caption(
        "One scenario is illustrative, not statistical proof. In the completed 150-scenario RFT evaluation, "
        "RFT averaged 0.826 reward with 98% feasibility. Run the same held-out set for SFT before making a formal aggregate RFT-versus-SFT claim."
    )

    if left_model == "Supervised fine-tuned (SFT)" and right_model == "Reinforcement fine-tuned (RFT)" and right_record["result"]["score"] > left_record["result"]["score"]:
        st.info(
            "Both plans are operationally valid and deliver every order on time. The distinction is optimization quality: "
            "SFT uses paid expedite service for O2, while RFT rearranges O2 and O3 across warehouses to avoid expedite entirely. "
            "RFT preserves full service and margin at lower shipping cost, producing the higher reward."
        )

st.divider()
st.header("What each fine-tuning method learned")
training_sft, training_rft, training_teacher = st.columns(3)
with training_sft:
    st.subheader("SFT")
    st.markdown(
        "The teacher generated three candidate plans for every fixed scenario. The best feasible response was retained only when its grader score was at least **0.75**. "
        "The enhanced dataset contained **148 training** and **38 validation** examples. SFT learns to imitate those curated target answers."
    )
with training_rft:
    st.subheader("RFT")
    st.markdown(
        "RFT trained on **300 scenarios** and validated on **60**. It generated plans during training and received outcome feedback: invalid plans scored zero; feasible plans were rewarded for priority-weighted on-time service, retained margin, and controlled cost. "
        "This repeated feedback teaches cross-order resource tradeoffs, not only answer imitation."
    )
with training_teacher:
    st.subheader("Teacher")
    st.markdown(
        "The teacher is not task fine-tuned. It receives the complete natural-language business prompt plus current operational data. It is useful as a strong prompt-only baseline and as the source of high-quality labels for SFT."
    )

with st.expander("Grader contract"):
    st.markdown(
        "- Every order must appear exactly once.\n"
        "- Unavailable warehouses, incorrect quantities, prohibited substitutions, inventory overruns, capacity overruns, and budget overruns invalidate the entire plan.\n"
        "- Feasible reward weights priority-aware on-time service at **55%**, retained margin at **25%**, and cost efficiency at **20%**.\n"
        "- Approved substitutions retain 90% of margin; late shipments retain half of their remaining margin.\n"
        "- Deferring everything is feasible but earns zero, preventing shortcut behavior."
    )

st.caption("Recorded replay uses verified outputs captured from the original deployments on this exact scenario and recomputes all grader metrics locally. Live model output can vary and requires active Azure deployments.")
